model = dict(
    type='MVSimCLR',
    data_preprocessor=None,
    backbone=dict(
        type='SharedStemModel',
        in_channels=None, 
        stem_width=32, 
        block_width=2, 
        n_layers=2, 
        late_fusion=False
    ),
    neck=dict(
        type='NonLinearNeck',   
        in_channels=None,
        hid_channels=64,
        out_channels=64,
        num_layers=1,
        with_avg_pool=False,
    ),
    head=dict(
        type='ContrastiveHead',
        loss=dict(type='mmcls.CrossEntropyLoss'),
        temperature=0.2,     
    )
)